from collections.abc import Callable
from pathlib import Path
import os
import re
import secrets
import socket
import subprocess
from urllib.parse import quote, unquote, urlsplit


DEFAULT_PORTS = {
    "POSTGRES_PORT": 55432,
    "PAPER_WEB_PORT": 8765,
}


def allocate_ports(
    requested: dict[str, int] | None = None,
    is_port_available: Callable[[int], bool] | None = None,
) -> dict[str, int]:
    ports = requested or DEFAULT_PORTS
    checker = is_port_available or port_is_available
    allocated: dict[str, int] = {}
    reserved: set[int] = set()
    for name, start_port in ports.items():
        port = start_port
        while port in reserved or not checker(port):
            port += 1
        allocated[name] = port
        reserved.add(port)
    return allocated


def generate_ports_env(
    path: Path,
    is_port_available: Callable[[int], bool] | None = None,
) -> dict[str, int]:
    allocated = allocate_ports(is_port_available=is_port_available)
    write_ports_env(path, allocated)
    return allocated


def write_ports_env(path: Path, ports: dict[str, int]) -> None:
    postgres_port = ports["POSTGRES_PORT"]
    paper_web_port = ports["PAPER_WEB_PORT"]
    user, password, database = _resolve_postgres_credentials(path)
    path.write_text(
        "\n".join(
            [
                "# Generated by scripts/start.sh. Safe to delete and regenerate.",
                f"POSTGRES_PORT={postgres_port}",
                f"PAPER_WEB_PORT={paper_web_port}",
                f"POSTGRES_USER={user}",
                f"POSTGRES_PASSWORD={password}",
                f"POSTGRES_DB={database}",
                f"DATABASE_URL={_database_url(user, password, postgres_port, database)}",
                "BINANCE_WEBSOCKET_BASE_URL=wss://fstream.binance.com/market",
                "PAPER_STATE_PATH=runtime/paper-state.json",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _resolve_postgres_credentials(path: Path) -> tuple[str, str, str]:
    """Resolve Postgres credentials without ever falling back to a weak default.

    Precedence: explicit environment variables, then any value already persisted
    in the generated env file (so the password stays stable across regenerations
    and keeps matching the existing database volume), then a freshly generated
    URL-safe random password.
    """
    existing = _read_env_file(path)
    url_user, url_password, url_database = _credentials_from_database_url(existing.get("DATABASE_URL"))
    user = os.environ.get("POSTGRES_USER") or existing.get("POSTGRES_USER") or url_user or "crypto"
    database = os.environ.get("POSTGRES_DB") or existing.get("POSTGRES_DB") or url_database or "crypto_quant"
    password = (
        os.environ.get("POSTGRES_PASSWORD")
        or existing.get("POSTGRES_PASSWORD")
        or url_password
        or secrets.token_urlsafe(24)
    )
    return user, password, database


def _credentials_from_database_url(url: str | None) -> tuple[str | None, str | None, str | None]:
    if not url:
        return None, None, None
    try:
        parsed = urlsplit(url)
    except ValueError:
        return None, None, None
    database = unquote(parsed.path.lstrip("/")) if parsed.path else None
    return (
        unquote(parsed.username) if parsed.username is not None else None,
        unquote(parsed.password) if parsed.password is not None else None,
        database or None,
    )


def _database_url(user: str, password: str, postgres_port: int, database: str) -> str:
    return (
        "postgresql+psycopg://"
        f"{quote(user, safe='')}:{quote(password, safe='')}"
        f"@localhost:{postgres_port}/{quote(database, safe='')}"
    )


def _read_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def backfill_credentials_env(path: Path) -> None:
    """Ensure an existing generated env file carries Postgres credentials.

    Older env files (generated before the credentials were threaded through)
    only contain ports. Compose now requires POSTGRES_PASSWORD, so backfill the
    missing credentials while preserving the already-allocated ports — never
    reallocating ports on a host where the container may already be running.
    """
    existing = _read_env_file(path)
    if not existing:
        return
    if existing.get("POSTGRES_PASSWORD") and "DATABASE_URL" in existing:
        return
    try:
        postgres_port = int(existing.get("POSTGRES_PORT", DEFAULT_PORTS["POSTGRES_PORT"]))
        paper_web_port = int(existing.get("PAPER_WEB_PORT", DEFAULT_PORTS["PAPER_WEB_PORT"]))
    except ValueError:
        return
    write_ports_env(path, {"POSTGRES_PORT": postgres_port, "PAPER_WEB_PORT": paper_web_port})


def port_is_available(port: int) -> bool:
    if port in docker_published_ports():
        return False

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind(("0.0.0.0", port))
        except OSError:
            return False
    return True


def docker_published_ports(
    command_runner: Callable[[list[str]], str] | None = None,
) -> set[int]:
    runner = command_runner or _run_command
    try:
        output = runner(["docker", "ps", "--format", "{{.Ports}}"])
    except Exception:
        return set()

    return {int(match) for match in re.findall(r"(?::|\\[::\\]:)(\d+)->", output)}


def _run_command(command: list[str]) -> str:
    return subprocess.check_output(command, text=True, stderr=subprocess.DEVNULL)


if __name__ == "__main__":
    generate_ports_env(Path(".env.ports.generated"))
