from collections.abc import Callable
from pathlib import Path
import re
import socket
import subprocess


DEFAULT_PORTS = {
    "POSTGRES_PORT": 55432,
    "PAPER_WEB_PORT": 8765,
}


def allocate_ports(
    requested: dict[str, int] | None = None,
    is_port_available: Callable[[int], bool] | None = None,
) -> dict[str, int]:
    ports = requested or DEFAULT_PORTS
    checker = is_port_available or port_is_available
    allocated: dict[str, int] = {}
    reserved: set[int] = set()
    for name, start_port in ports.items():
        port = start_port
        while port in reserved or not checker(port):
            port += 1
        allocated[name] = port
        reserved.add(port)
    return allocated


def generate_ports_env(
    path: Path,
    is_port_available: Callable[[int], bool] | None = None,
) -> dict[str, int]:
    allocated = allocate_ports(is_port_available=is_port_available)
    write_ports_env(path, allocated)
    return allocated


def write_ports_env(path: Path, ports: dict[str, int]) -> None:
    postgres_port = ports["POSTGRES_PORT"]
    paper_web_port = ports["PAPER_WEB_PORT"]
    path.write_text(
        "\n".join(
            [
                "# Generated by scripts/start_ubuntu.sh. Safe to delete and regenerate.",
                f"POSTGRES_PORT={postgres_port}",
                f"PAPER_WEB_PORT={paper_web_port}",
                f"DATABASE_URL=postgresql+psycopg://crypto:crypto@localhost:{postgres_port}/crypto_quant",
                "BINANCE_WEBSOCKET_BASE_URL=wss://fstream.binance.com/market",
                "PAPER_STATE_PATH=runtime/paper-state.json",
                "",
            ]
        ),
        encoding="utf-8",
    )


def port_is_available(port: int) -> bool:
    if port in docker_published_ports():
        return False

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            sock.bind(("0.0.0.0", port))
        except OSError:
            return False
    return True


def docker_published_ports(
    command_runner: Callable[[list[str]], str] | None = None,
) -> set[int]:
    runner = command_runner or _run_command
    try:
        output = runner(["docker", "ps", "--format", "{{.Ports}}"])
    except Exception:
        return set()

    return {int(match) for match in re.findall(r"(?::|\\[::\\]:)(\d+)->", output)}


def _run_command(command: list[str]) -> str:
    return subprocess.check_output(command, text=True, stderr=subprocess.DEVNULL)


if __name__ == "__main__":
    generate_ports_env(Path(".env.ports.generated"))
